import java.sql.*;
import javax.swing.JOptionPane;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * f1.java
 *
 * Created on Dec 2, 2015, 2:59:28 PM
 */

/**
 *
 * @author student
 */
public class f1 extends javax.swing.JFrame {

    /** Creates new form f1 */
    public f1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Paathshala");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 270, 50));

        jLabel3.setFont(new java.awt.Font("Candara", 3, 24));
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("path to success......");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 190, -1));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Aparajita", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 570, 410));

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Contact Us");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
this.dispose();
new home().setVisible(true);
   



        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
this.dispose();
new about().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
this.dispose();
new contact().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
 try {
     Class.forName("java.sql.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
     Statement st =con.createStatement();
     String q= " create table administrator(name varchar (20),login_id varchar (20) primary key, password varchar (20), contact_no numeric(10)) ;";
     String x= " create table student(name varchar (20),scholar_no numeric (6) primary key, father_name varchar (20), class integer(2), mobile_no numeric(10), joining_date date , fees numeric(6));";
     String w= " create table parent(name varchar (20),scholar_no numeric (6) , login_id varchar (20) primary key, password varchar (20), contact_no numeric(10)) ;";
     String z= " create table fees(Student_name varchar (20),scholar_no numeric (6) , class numeric(2),installment_no numeric(10), installment_date date, installment_amount numeric(6), paid varchar(6));";
     String p= " create table class_9(name varchar(20), scholar_no numeric(6) primary key,present varchar(4),absent varchar(4)) ;" ;
     String c= " create table class_10(name varchar(20), scholar_no numeric(6) primary key,present varchar(4),absent varchar(4)) ;" ;
     String v= " create table class_11(name varchar(20), scholar_no numeric(6) primary key,present varchar(4),absent varchar(4)) ;" ;
     String b= " create table class_12(name varchar(20), scholar_no numeric(6) primary key,present varchar(4),absent varchar(4)) ;" ;

      
       st.executeUpdate(x);
       st.executeUpdate(q);
        st.executeUpdate(w);
        st.executeUpdate(z);
        st.executeUpdate(p);
       st.executeUpdate(c);
       st.executeUpdate(v);
      st.executeUpdate(b);
       

     JOptionPane.showMessageDialog(null,"Ready for use");
     
 }
  catch(Exception e){
   JOptionPane.showMessageDialog(null,e.getMessage());

  }



        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
try {
     Class.forName("java.sql.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
     Statement st =con.createStatement();
        String q= " delete from student ;";
        String w= " delete from parent ;";
        String x= " delete from fees ;";
        String y= " delete from administrator ;";
        String z= " delete from class_9 ;";
        String p= " delete from class_10 ;";
        String h= " delete from class_11 ;";
        String i= " delete from class_12 ;";
        st.executeUpdate(x);
       st.executeUpdate(q);
        st.executeUpdate(w);
        st.executeUpdate(z);
        st.executeUpdate(p);
       st.executeUpdate(h);
       st.executeUpdate(y);
      st.executeUpdate(i);


     JOptionPane.showMessageDialog(null,"Record Deleted");

 }
  catch(Exception e){
   JOptionPane.showMessageDialog(null,e.getMessage());

  }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
