import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newst.java
 *
 * Created on Dec 2, 2015, 3:14:11 PM
 */

/**
 *
 * @author student
 */
public class newst extends javax.swing.JFrame {

    /** Creates new form newst */
    public newst() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d1 = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        td1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        p5 = new javax.swing.JTextField();
        p6 = new javax.swing.JTextField();
        p7 = new javax.swing.JTextField();
        p8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tt1 = new javax.swing.JTextField();

        d1.setMinimumSize(new java.awt.Dimension(500, 500));
        d1.setModal(true);
        d1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Total Fees");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        d1.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 20));

        td1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                td1ActionPerformed(evt);
            }
        });
        d1.getContentPane().add(td1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, -1));

        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        d1.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 255, 255));
        jLabel6.setFont(new java.awt.Font("Aparajita", 3, 48));
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel6.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jLabel6.setOpaque(true);
        d1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel12.setText("Installment No.");
        d1.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 30));

        jLabel13.setText("Amount");
        d1.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 70, 20));

        jLabel14.setText("Date (YYYY-MM-DD)");
        d1.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 110, 20));

        jLabel15.setText("1");
        d1.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel16.setText("2");
        d1.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel18.setText("4");
        d1.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));
        d1.getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 50, -1));
        d1.getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 50, -1));
        d1.getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 50, -1));
        d1.getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 50, -1));

        jLabel19.setText("3");
        d1.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 30, -1));
        d1.getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 60, -1));
        d1.getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 60, -1));
        d1.getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 60, -1));
        d1.getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 60, -1));

        jLabel11.setBackground(new java.awt.Color(0, 255, 255));
        jLabel11.setFont(new java.awt.Font("Aparajita", 3, 48));
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel11.setMinimumSize(new java.awt.Dimension(300, 300));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(500, 500));
        d1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 510, 610));

        jLabel17.setText("3");
        d1.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 10, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 50, 20));

        jLabel3.setText("Class");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel4.setText("Scholar No.");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel5.setText("Father's Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, 20));

        jLabel7.setText("Joining Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 20));

        jButton1.setText("Fee Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, 50));

        jLabel8.setText("Mobile No.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 60, 20));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 80, -1));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 80, -1));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, -1));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 80, -1));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 80, -1));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 80, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jLabel9.setText("Total Fees");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 60, 20));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 80, 20));

        jLabel10.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Aparajita", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 410));

        tt1.setText("jTextField1");
        getContentPane().add(tt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
d1.setVisible(true);




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new adminlogin().setVisible(true);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new adminlogin().setVisible(true);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int p = Integer.parseInt(p1.getText());
int q = Integer.parseInt(p2.getText());
int r = Integer.parseInt(p3.getText());
int s = Integer.parseInt(p4.getText());
int g = p+q+r+s;
td1.setText("" + g);
t7.setText("" + g);


// TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    private void td1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_td1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_td1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String a = t1.getText();
int b = Integer.parseInt(t2.getText());
String c = t3.getText();
int p = Integer.parseInt(p1.getText());
int q = Integer.parseInt(p2.getText());
int r = Integer.parseInt(p3.getText());
int s = Integer.parseInt(p4.getText());

String t = p5.getText();
String u = p6.getText();
String v = p7.getText();
String w = p8.getText();


int i=1;
int j=2;
int k=3;
int l=4;

 try
 {
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
Statement st= con.createStatement();
String m = " Insert into fees ( Student_name, scholar_no, class, installment_no, installment_date, installment_amount, paid) values ('"+a+"',"+b+","+c+","+i+",'"+t+"',"+p+",'no'), ('"+a+"',"+b+","+c+","+j+",'"+u+"',"+q+",'no'), ('"+a+"',"+b+","+c+","+k+",'"+v+"',"+r+",'no'), ('"+a+"',"+b+","+c+","+l+",'"+w+"',"+s+",'no') ; ";

st.executeUpdate(m);
JOptionPane.showMessageDialog(null,"Record Added");
}

 catch (Exception e)

{JOptionPane.showMessageDialog(null,e.getMessage());
}










 // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String a = t1.getText();
int b = Integer.parseInt(t2.getText());
int c = Integer.parseInt(t3.getText());
String d = t4.getText();
int j = Integer.parseInt(t5.getText());
String f = t6.getText();
int k = Integer.parseInt(t7.getText());
try {

Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
Statement st= con.createStatement();
String q = " Insert into student values ('"+a+"',"+b+",'"+d+"',"+c+","+j+",'"+f+"',"+k+");";
st.executeUpdate(q);
JOptionPane.showMessageDialog(null,"Record Added");
}
catch (Exception e)

{JOptionPane.showMessageDialog(null,e.getMessage());

}
String p="";
switch(c) {
    case(9): p="class_9";
    break;
    case(10): p = "class_10";
     break;
    case(11): p = "class_11";
     break;
    case(12): p = "class_12";
     break;
}

try
{
Class.forName("java.sql.Driver");
Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
Statement st =conn.createStatement();
String u = " Insert into "+p+" values('"+a+"','"+b+"',0,0);";
st.executeUpdate(u);


}
catch(Exception e){
JOptionPane.showMessageDialog(null,e.getMessage());
}











// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
tt1.setVisible(false);
        try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
    Statement st = con.createStatement();
    String q = "Select max(scholar_no) from student ;";
    ResultSet rs = st.executeQuery(q);
    if (rs.next()){
       
        String a=rs.getString("max(scholar_no)");
      tt1.setText(""+a);
     
      
      int b = Integer.parseInt(a);
      t2.setText(""+(b+1));
      
    }


    
}
catch (Exception e)
{}
String c=tt1.getText();
if(c.compareTo("null")==0)
    t2.setText(""+1);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog d1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JTextField p7;
    private javax.swing.JTextField p8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField td1;
    private javax.swing.JTextField tt1;
    // End of variables declaration//GEN-END:variables

}
