import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewatten.java
 *
 * Created on Dec 2, 2015, 3:02:02 PM
 */

/**
 *
 * @author student
 */
public class viewatten extends javax.swing.JFrame {

    /** Creates new form viewatten */
    public viewatten() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Class 9");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jButton2.setText("Class 10");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jButton3.setText("Class 11");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jButton4.setText("Class 12");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel2.setText("View Attendance");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 100, 30));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Scholar No.", "Present", "Absent"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 340, 90));

        jButton7.setText("Empty Table");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Aparajita", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        new adminlogin().setVisible(true);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        new adminlogin().setVisible(true);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel model=(DefaultTableModel)tb1.getModel();
try
{
Class.forName("java.sql.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
Statement st =con.createStatement();
String q= "select * from class_9  ;";
ResultSet rs = st.executeQuery(q);
while(rs.next())
{String c=rs.getString("scholar_no");
 String b=rs.getString("name");
 String d=rs.getString("present");
 String e=rs.getString("absent");


  model.addRow(new Object[] {b,c,d,e} );

}

}


catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel model=(DefaultTableModel)tb1.getModel();
try
{
Class.forName("java.sql.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
Statement st =con.createStatement();
String q= "select * from class_10  ;";
ResultSet rs = st.executeQuery(q);
while(rs.next())
{String c=rs.getString("scholar_no");
 String b=rs.getString("name");
 String d=rs.getString("present");
 String e=rs.getString("absent");


  model.addRow(new Object[] {b,c,d,e} );

}

     
}


catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DefaultTableModel model=(DefaultTableModel)tb1.getModel();
try
{
Class.forName("java.sql.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
Statement st =con.createStatement();
String q= "select * from class_11  ;";
ResultSet rs = st.executeQuery(q);
while(rs.next())
{String c=rs.getString("scholar_no");
 String b=rs.getString("name");
 String d=rs.getString("present");
 String e=rs.getString("absent");


  model.addRow(new Object[] {b,c,d,e} );

}

}


catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
DefaultTableModel model=(DefaultTableModel)tb1.getModel();
try
{
Class.forName("java.sql.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
Statement st =con.createStatement();
String q= "select * from class_12  ;";
ResultSet rs = st.executeQuery(q);
while(rs.next())
{String c=rs.getString("scholar_no");
 String b=rs.getString("name");
 String d=rs.getString("present");
 String e=rs.getString("absent");


  model.addRow(new Object[] {b,c,d,e} );

}

}


catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int ans=JOptionPane.showConfirmDialog(null,"Do You Really Want To Empty The Table ? ");
        if (ans==JOptionPane.YES_OPTION) {

            DefaultTableModel model =(DefaultTableModel)tb1.getModel();
            int r=model.getRowCount();
            if(r>0) {
                int  i=0;
                while(i<r) {
                    model.removeRow(0);
                    i++;
                }

            }

        }        // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewatten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

}
